Change to set custom define ghq command
Jagua/vim-denite-ghq pull request #1
Opened 2021-01-07 06:30 UTC by w1mvy

Hi! this plugin is nice and helpful for me!

I changed to ghq command can be defined by the user.

## Motivation

ghq v0.13.1 optimized `--vcs` option of `ghq list`.
I only use git, so I want to use this option.

2021-01-11 16:16 UTC, Jagua requested changes

2021-01-11 16:16 UTC, Jagua commented on readme.mkd
> +```
Give language identifier `vim` in fenced code block.
And change to Vim's comment command like the following.

    ```vim
    " Use vcs option

2021-01-11 23:29 UTC, w1mvy commented on readme.mkd
> +```
@Jagua Thanks for your comment, and I fixed it!
https://github.com/Jagua/vim-denite-ghq/pull/1/commits/2c65d5c1f0d68d3443265fc8544add0c447cbce4

2021-01-12 14:39 UTC, Jagua commented on readme.mkd
> +```
Please give language identifier `vim` in fenced code block.

    ```vim

2021-01-12 21:21 UTC, w1mvy commented on readme.mkd
> +```
Sorry I overlooked it and changed it.

2021-01-13 15:36 UTC, merged

2021-01-13 15:37 UTC, Jagua commented
Merged. Thank you for sending Pull Request!

2021-01-15 00:45 UTC, w1mvy commented
Thank you for review & merge!!